#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Define colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}====================================================${NC}"
echo -e "${GREEN}      Bookngon AI - Virtual Receptionist Setup      ${NC}"
echo -e "${GREEN}====================================================${NC}"

# Check Python installation
echo -e "\n${YELLOW}[1/7] Checking Python installation...${NC}"
if command -v python3 &>/dev/null; then
    PYTHON_CMD="python3"
    echo -e "${GREEN}Found Python 3: $(python3 --version)${NC}"
elif command -v python &>/dev/null; then
    PYTHON_CMD="python"
    echo -e "${GREEN}Found Python: $(python --version)${NC}"
else
    echo -e "${RED}Error: Python is not installed. Please install Python 3 and try again.${NC}"
    exit 1
fi

# Create virtual environment
echo -e "\n${YELLOW}[2/7] Setting up virtual environment 'env'...${NC}"
if [ -d "env" ]; then
    echo -e "Virtual environment 'env' already exists. Skipping creation."
else
    $PYTHON_CMD -m venv env
    echo -e "${GREEN}Created virtual environment 'env'.${NC}"
fi

# Activate virtual environment
echo -e "\n${YELLOW}[3/7] Activating virtual environment...${NC}"
# shellcheck disable=SC1091
source env/bin/activate
echo -e "${GREEN}Virtual environment activated.${NC}"

# Upgrade pip
echo -e "\n${YELLOW}[4/7] Upgrading pip...${NC}"
pip install --upgrade pip

# Install requirements
echo -e "\n${YELLOW}[5/7] Installing dependencies from requirements.txt...${NC}"
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
    # Ensure django-webpush is installed correctly and not overridden by conflicting webpush package
    echo -e "${YELLOW}Ensuring django-webpush is cleanly installed...${NC}"
    pip uninstall -y webpush 2>/dev/null || true
    pip install --force-reinstall django-webpush==0.3.6
    echo -e "${GREEN}Dependencies installed successfully.${NC}"
else
    echo -e "${RED}Error: requirements.txt not found.${NC}"
    exit 1
fi

# Setup env variables
echo -e "\n${YELLOW}[6/7] Setting up environment variables (.env)...${NC}"
if [ -f ".env" ]; then
    echo -e "An existing .env file was found. Keeping it."
else
    if [ -f ".env.example" ]; then
        cp .env.example .env
        echo -e "${GREEN}Created .env from .env.example.${NC}"
        echo -e "${YELLOW}Please remember to edit .env with your own API keys (e.g. OpenAI, Twilio, Stripe).${NC}"
    else
        echo -e "${RED}Warning: .env.example not found. Could not generate .env.${NC}"
    fi
fi

# Create necessary directories (like logs/)
echo -e "\n${YELLOW}[7/7] Creating necessary directories...${NC}"
mkdir -p logs
echo -e "${GREEN}Created 'logs/' directory for Django logging.${NC}"

# Fix webpush package missing migration
echo -e "\n${YELLOW}[Patch] Checking for third-party webpush migration patch...${NC}"
WEBPUSH_MIGRATIONS_DIR=$(find env/lib -type d -path "*/site-packages/webpush/migrations" 2>/dev/null | head -n 1)
if [ -n "$WEBPUSH_MIGRATIONS_DIR" ] && [ -d "$WEBPUSH_MIGRATIONS_DIR" ]; then
    if [ ! -f "$WEBPUSH_MIGRATIONS_DIR/0006_alter_subscriptioninfo_user_agent.py" ]; then
        cat << 'EOF' > "$WEBPUSH_MIGRATIONS_DIR/0006_alter_subscriptioninfo_user_agent.py"
# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpush', '0005_auto_20230614_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
EOF
        echo -e "${GREEN}Applied patch for webpush package migrations.${NC}"
    else
        echo -e "Webpush package migration patch already applied."
    fi
else
    echo -e "${RED}Warning: webpush package migrations directory not found. Could not apply patch.${NC}"
fi

# Run Database Migrations
echo -e "\n${YELLOW}[Bonus] Running database migrations...${NC}"
if [ -f "manage.py" ]; then
    python manage.py migrate
    echo -e "${GREEN}Migrations applied successfully.${NC}"
else
    echo -e "${RED}Warning: manage.py not found. Skipping migrations.${NC}"
fi

echo -e "\n${GREEN}====================================================${NC}"
echo -e "${GREEN}Setup completed successfully!${NC}"
echo -e "To start developing:"
echo -e "  1. Activate the environment:  ${YELLOW}source env/bin/activate${NC}"
echo -e "  2. Start the servers:        ${YELLOW}make run-both${NC} or ${YELLOW}make run${NC}"
echo -e "${GREEN}====================================================${NC}"
